# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_ariticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariticle',
            name='tag',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('life', 'Life')], max_length=5, null=True),
        ),
    ]
